# Generated by Django 4.0.5 on 2022-12-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
